version: "2.2"

services:
    frontend:
        image: ember-dev:3.14.0
            # Keep the stdin open, so we can attach to our app container's process
        # and do things such as debugging, etc
        stdin_open: true
        # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
        tty: true
        ports:
            # TODO: Change production image to 4200 instead of 8080
            # so dont have to override here
            # server
            - 4200:4200
            # livereload
            - 7020:7020
            # Tests in browser
            - 7357:7357
        volumes:
            - ./frontend:/home/node/app
    backend:
        image: dflow-ruby-2.3:latest
        depends_on:
            - db
        environment:
            - DFLOW_DB_HOST=db
            - DFLOW_DB_PORT=5432
            - DFLOW_DB=dflow_dev_local
            - DFLOW_DB_USER=postgres
            - DFLOW_DB_PASSWORD=password
        ports:
            - 3000:3000
        volumes:
            - ./backend:/usr/src/app
        command: ["sh", "-c", "bundle install && rails server -b 0.0.0.0 -e development"]
    db:
        image: postgres:9.4
        environment:
            - POSTGRES_DB=dflow_dev_local
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=password
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
