version: "3.5"

services:
    frontend:
        # Keep the stdin open, so we can attach to our app container's process
        # and do things such as debugging, etc
        stdin_open: true
        # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
        tty: true
        environment:
            - EMBER_ENVIRONMENT=${DFLOW_ENVIRONMENT}
            - DFLOW_SERVICE_PORT=${DFLOW_BACKEND_PORT}
    backend:
        depends_on:
            - db
        environment:
            - ENVIRONMENT=${DFLOW_ENVIRONMENT}
            - DFLOW_DB_HOST=${DFLOW_DB_HOST}
            - DFLOW_DB_PORT=${DFLOW_DB_PORT}
            - DFLOW_DB=${DFLOW_DB}
            - DFLOW_DB_USER=${DFLOW_DB_USER}
            - DFLOW_DB_PASSWORD=${DFLOW_DB_PASSWORD}
        ports:
            - ${DFLOW_BACKEND_PORT}:${DFLOW_RAILS_PORT}
    db:
        restart: always
        environment:
            - POSTGRES_DB=${DFLOW_DB}
            - POSTGRES_USER=${DFLOW_DB_USER}
            - POSTGRES_PASSWORD=${DFLOW_DB_PASSWORD}
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data

volumes:
    dbdata:
