version: "3.5"

services:
    frontend:
        # Keep the stdin open, so we can attach to our app container's process
        # and do things such as debugging, etc
        stdin_open: true
        # Enable sending signals (CTRL+C, CTRL+P + CTRL+Q) into the container
        tty: true
        environment:
            - EMBER_ENVIRONMENT=${ENVIRONMENT}
            - SERVICE_HOSTNAME=${DFLOW_RAILS_SERVICE_HOSTNAME}
            - BACKEND_SERVICE_PORT=${DFLOW_RAILS_SERVICE_PORT}
    backend:
        depends_on:
            - db
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - DB_HOST=${DB_HOST}
            - DB_PORT=5432
            - DB=${DB}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - SECRET_KEY_BASE=${DFLOW_SECRET_KEY_BASE}
            - DFILE_RAILS_SERVICE_HOSTNAME_AND_PORT=${DFILE_RAILS_SERVICE_HOSTNAME_AND_PORT}
            - DFILE_API_KEY=${DFILE_API_KEY}
        ports:
        - ${DFLOW_RAILS_SERVICE_PORT}:3000
    db:
        restart: always
        environment:
            - POSTGRES_DB=${DB}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        volumes:
            - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
            - dbdata:/var/lib/postgresql/data
    dfile:
        depends_on:
            - redis
        environment:
            - ENVIRONMENT=${ENVIRONMENT}
            - SECRET_KEY_BASE=${DFILE_SECRET_KEY_BASE}
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
        ports:
            - ${DFILE_RAILS_SERVICE_PORT}:3000
    redis:
        image: redis:6.0.10
        volumes:
            - redis:/data
        command: redis-server

volumes:
    redis:
    dbdata:
