# List of available events (used for job activity entries)
events:
  -
    name: QUARANTINE
  -
    name: UNQUARANTINE
  -
    name: CREATE
  -
    name: UPDATE
  -
    name: CHANGE_STATUS
  -
    name: DELETE
  -
    name: FLOW_STEP
  -
    name: RESTART
  -
    name: STATUS
  -
    name: STARTED
  -
    name: FINISHED


