# Defines the format of the package name
package_name: GUB%07d

# Defines the layout and contents of job work order pdf (used in app/models/pdf_helper.rb)
pdf_settings:
  operators: "[ ] Maria     [ ] Grim     [ ] Ingela"
  equipments: "[ ] Robot    [ ] Zeutschel    [ ] Canon "

# Defines the selectable publicationLog types
publication_types:
  - 'MANUSCRIPT'
  - 'WIKIPEDIA'
  - 'GUPEA'
  - 'LIBRIS'
    
