---

### USER ROLES DEFINITION
### Create a new role by adding another hash with a unique name of the role as well as a list of rights. Unassignable states that the role cannot be assigned to users.
### Available rights are: 'view_users', 'manage_users', 'view_tree', 'manage_tree', 'manage_tree_root'
user_roles:
  -
    name: ADMIN
    rights:
      - view_users
      - manage_users
      - view_tree
      - manage_tree
      - manage_tree_root
      - manage_jobs
  -
    name: GUEST
    rights:
      - view_tree
    unassignable: true
  -
    name: OPERATOR
    rights:
      - view_tree
      - manage_tree
      - manage_jobs
  -
    name: API_KEY
    rights:
      - view_tree
      - manage_tree
      - manage_tree_root
      - manage_jobs
      - manage_users
      - view_users
    unassignable: true

# Flags for using external authentication source
external_auth: false

# Adapter for file management
file_adapter: dfile

# List of available sources
sources:
  -
    name: libris
    label: Libris
    class_name: Libris
  -
    name: dc
    label: DC
    class_name: DublinCore
  -
    name: dcxml
    label: DC-XML
    class_name: DublinCoreXML
  -
    name: document
    label: Document
    class_name: Document
  -
    name: letter
    label: Letter
    class_name: Letter

# List of available events (used for job activity entries)
events:
  -
    name: QUARANTINE
  -
    name: UNQUARANTINE
  -
    name: CREATE
  -
    name: UPDATE
  -
    name: CHANGE_STATUS
  -
    name: DELETE
  -
    name: FLOW_STEP
  -
    name: RESTART
  -
    name: STATUS
  -
    name: STARTED
  -
    name: FINISHED

# Defines the format of the package name
package_name: GUB%07d

# Defines the layout and contents of job work order pdf (used in app/models/pdf_helper.rb)
pdf_settings:
  operators: "[ ] Maria     [ ] Grim     [ ] Ingela"
  equipments: "[ ] Robot    [ ] Zeutschel    [ ] Canon "

# Defines the selectable publicationLog types
publication_types:
  - 'MANUSCRIPT'
  - 'WIKIPEDIA'
  - 'GUPEA'
  - 'LIBRIS'
    
