---
_is_setup: true
username: 'admin'
password: '1234'
_db:
  info: "Ange databasinställningar nedan"
  system: true
db:
  _host:
    info: "Ange adress till databasen, ex. localhost"
  host: 'localhost'
  port: '5432'
  username: postgres
  password:
  database: dflow_test
  pool: 5
  timeout: 5000

_external_auth:
  info: "Välj ifall en extern inloggningstjänst skall användas"
  type: radio
  options:
    - true
    - false
  system: true
_cas_url:
  system: true
cas_url: https://example.com/login
_file_adapter:
  system: true
file_adapter: dfile
package_name: GUB%07d
pdf_settings:
  operators: "[ ] Maria     [ ] Grim     [ ] Ingela"
  equipments: "[ ] Robot    [ ] Zeutschel    [ ] Canon "
user_roles:
- name: OPERATOR
  rights:
  - view_tree
  - manage_tree
  - manage_jobs
api_key_users:
  -
    username: test_key_user
    name: Test key User
    role: API_KEY
    api_key: test_key
# External authentication source
external_auth_url: "https://login-server.example.org/auth"

## dFile Parameters
dfile_base_url: "http://dfile.example.org"
dfile_api_key: test_key

dcat_base_url: "http://dcat.example.org"
dcat_api_key: test_key

external_auth: true

redis_db:
  db: 1
  host: localhost
workflows:
  -
    name: VALID_FLOW
    steps:
      -
        step: 10
        process: CONFIRMATION
        description: Waiting to begin
        goto_true: 20
        goto_false:
        params:
          start: true
          manual: true
          msg: Start flow
      -
        step: 20
        process: CONFIRMATION
        description: First manual process
        goto_true: 30
        goto_false:
        params:
          manual: false
          msg: Confirm manual process done
      -
        step: 30
        process: AUTOMATIC_PROCESS
        description: First automatic process
        goto_true: 40
        goto_false:
        params:
          manual: false
      -
        step: 40
        process: AUTOMATIC_PROCESS
        description: Final automatic process
        goto_true: 50
        goto_false:
        params:
          manual: false
      -
        step: 50
        process: CONFIRMATION
        description: Manually triggered process
        goto_true:
        goto_false:
        params:
          manual: true
  -
    name: MISSING_GOTO_STEP
    steps:
      -
        step: 10
        process: CONFIRMATION
        description: Väntar på digitalisering
        goto_true: 200
        goto_false:
        params:
          manual: true
          msg: Starta digitalisering
  -
    name: DUPLICATE_STEP
    steps:
      -
        step: 10
        process: CONFIRMATION
        description: Väntar på digitalisering
        goto_true: 10
        goto_false:
        params:
          manual: true
          msg: Starta digitalisering
      -
        step: 10
        process: CONFIRMATION
        description: Väntar på digitalisering
        goto_true: 10
        goto_false:
        params:
          manual: true
          msg: Starta digitalisering
  -
    name: MISSING_PARAMS
    steps:
      -
        step: 10
        process: CONFIRMATION
        description: Väntar på digitalisering
        goto_true: 10
        goto_false:
        params:
          msg: Starta digitalisering
  -
    name: CIRCULAR_REFERENCE
    steps:
      -
        step: 10
        process: CONFIRMATION
        description: Waiting to begin
        goto_true: 20
        goto_false:
        params:
          start: true
          manual: true
          msg: Start flow
      -
        step: 20
        process: CONFIRMATION
        description: First manual process
        goto_true: 30
        goto_false:
        params:
          manual: false
          msg: Confirm manual process done
      -
        step: 30
        process: AUTOMATIC_PROCESS
        description: First automatic process
        goto_true: 40
        goto_false: 10
        params:
          manual: false
      -
        step: 40
        process: AUTOMATIC_PROCESS
        description: Final automatic process
        goto_true:
        goto_false:
        params:
          manual: false

default_workflow: VALID_FLOW
queue_manager:
  processes:
    mets:
      CREATOR:
        name: "Test library"
        sigel: "Sig"

      ARCHIVIST:
        name: "Test archivist"
        sigel: "Sig"

      COPYRIGHT_STATUS:
        'true': "copyrighted"
        'false': "pd"

      PUBLICATION_STATUS:
        'true': "unpublished"
        'false': "unpublished"
    import_metadata:
      require_physical: true
      validate_group_name: true
