### API KEY USED FOR API-CALLS
api_key: test_key
# External authentication source
external_auth_url: "https://login-server.example.com/auth"

# Path prefix to STORE-PDF
pdf_path_prefix_store: "http://localhost:3001/download_file?source_file=STORE:"
pdf_path_prefix_packaging: "http://localhost:3001/download_file?source_file=PACKAGING:"